//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerReportConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_FilesReport
    {
        public L_FilesReport()
        {
            this.L_ParamReports = new HashSet<L_ParamReports>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_reports { get; set; }
        public int id_subsribes { get; set; }
        public int id_format { get; set; }
        public string place_save_local { get; set; }
        public Nullable<int> id_place_save_sp { get; set; }
        public bool sendmail { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string who_create { get; set; }
    
        public virtual L_Subscribes L_Subscribes { get; set; }
        public virtual S_ParamSys S_ParamSysFormat { get; set; }
        public virtual S_ParamSys S_ParamSysPlaceSaveSp { get; set; }
        public virtual S_Reports S_Reports { get; set; }
        public virtual ICollection<L_ParamReports> L_ParamReports { get; set; }
    }
}
