//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerReportConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Schedule
    {
        public L_Schedule()
        {
            this.L_Subscribes = new HashSet<L_Subscribes>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_type_schedule { get; set; }
        public System.TimeSpan time_schedule { get; set; }
        public Nullable<System.DateTime> datetime_start { get; set; }
        public Nullable<System.DateTime> datetime_end { get; set; }
        public int id_type_period { get; set; }
        public int dur_period { get; set; }
        public Nullable<System.DateTime> datemonth_start { get; set; }
        public Nullable<System.DateTime> datemonth_end { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string who_create { get; set; }
    
        public virtual S_ParamSys S_ParamSysTypePeriod { get; set; }
        public virtual S_ParamSys S_ParamSysTypeSchedule { get; set; }
        public virtual ICollection<L_Subscribes> L_Subscribes { get; set; }
    }
}
