//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerReportConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Subscribes
    {
        public L_Subscribes()
        {
            this.L_FilesReport = new HashSet<L_FilesReport>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_schedule { get; set; }
        public string email { get; set; }
        public string email_test { get; set; }
        public Nullable<System.Guid> file_template_success { get; set; }
        public Nullable<System.Guid> file_template_warning { get; set; }
        public Nullable<System.DateTime> datetime_start { get; set; }
        public Nullable<System.DateTime> datetime_end { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string who_create { get; set; }
    
        public virtual ICollection<L_FilesReport> L_FilesReport { get; set; }
        public virtual L_Schedule L_Schedule { get; set; }
    }
}
