//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerReportConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ManagerReportsEntities : DbContext
    {
        public ManagerReportsEntities()
            : base("name=ManagerReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<L_FilesReport> L_FilesReport { get; set; }
        public DbSet<L_ParamReports> L_ParamReports { get; set; }
        public DbSet<L_Schedule> L_Schedule { get; set; }
        public DbSet<L_Subscribes> L_Subscribes { get; set; }
        public DbSet<S_ParamDirectory> S_ParamDirectory { get; set; }
        public DbSet<S_ParamSys> S_ParamSys { get; set; }
        public DbSet<S_Reports> S_Reports { get; set; }
    
        public virtual ObjectResult<ViewFileReport_Result> ViewFileReport(Nullable<int> id_subsribes)
        {
            var id_subsribesParameter = id_subsribes.HasValue ?
                new ObjectParameter("id_subsribes", id_subsribes) :
                new ObjectParameter("id_subsribes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewFileReport_Result>("ViewFileReport", id_subsribesParameter);
        }
    }
}
