//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerReportConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Reports
    {
        public S_Reports()
        {
            this.L_FilesReportReport = new HashSet<L_FilesReport>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string path_report { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<L_FilesReport> L_FilesReportReport { get; set; }
    }
}
